# Generated by Django 3.2.7 on 2022-08-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_compression', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dwt_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dwt_images')),
            ],
        ),
    ]
